spring.application.name=motogp

# Conexion BBDD
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${POSTGRES_DB:motogp}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:ahmfa!}

# Config JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port= 8081

spring.jackson.mapper.allow-coercion-of-scalars=false


# Official league
official.league.id=1
