spring.application.name=motogp

# Conexion BBDD
spring.datasource.url=jdbc:postgresql://localhost:5432/motogp
spring.datasource.username=postgres
spring.datasource.password=ahmfa!

# Config JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jackson.mapper.allow-coercion-of-scalars=false
